### ISSUE TITLE
Bug with Joyride, Touring incorrectly.

### ISSUE THREAD

**Issue by stndlkr200** [walterbender/turtleblocksjs#140]
While you take tour to Turtle Blocks, 
After Expand/collapse collapsable blocksExpand/collapse  tour is not according to subject.
I will start fixing it tonight. [~Abhishek ]
![screenshot from 2015-01-30 12 11 05](https://cloud.githubusercontent.com/assets/4478973/5972100/bfd378c8-a879-11e4-91e1-c5db39e9e8cb.png)
![screenshot from 2015-01-30 12 10 29](https://cloud.githubusercontent.com/assets/4478973/5972105/d113eb54-a879-11e4-95ff-72a634349f21.png)
![screenshot from 2015-01-30 12 08 51](https://cloud.githubusercontent.com/assets/4478973/5972160/f7907094-a87a-11e4-9939-381b71eaeb0d.png)

**Comment by walterbender** [comment]
replaced the joyride code with native createJS code.

**Comment by stndlkr200** [comment]
Thanks :)
