### ISSUE TITLE
Mouse events are not binded properly with co-ordinates on canvas.

### ISSUE THREAD

**Issue by stndlkr200** [walterbender/turtleblocksjs#142]
Currently in the "Toolbar" on top, mouse events like click and drag doesn't point to specific element/toolbar because of co-ordinates detection mechanism on canvas.
Tough its not a serious issue but improving it will be great.
I would like to discuss ways other than co-ordinate detection too.
Attaching some images where my mouse is not on the element but i can trigger the event.
![screenshot from 2015-01-31 17 44 37](https://cloud.githubusercontent.com/assets/4478973/5988062/445dba7c-a974-11e4-8109-48782423a8c4.png)
![screenshot from 2015-01-31 18 06 50](https://cloud.githubusercontent.com/assets/4478973/5988063/46fd6f16-a974-11e4-9e06-17ce2a09984e.png)
![screenshot from 2015-01-31 18 08 36](https://cloud.githubusercontent.com/assets/4478973/5988065/4d229cb8-a974-11e4-9101-342080da1497.png)

**Comment by SAMdroid-apps** [comment]
This is patched by #192 for some reason :smile:

**Comment by stndlkr200** [comment]
This looks nice now :+1:

**Comment by SAMdroid-apps** [comment]
Can we close this issue?

**Comment by stndlkr200** [comment]
Done, closed the ticket: http://bugs.sugarlabs.org/ticket/4817#comment:3
I am happy that all the bug reported by me has been fixed. 
Walter : Joyride  Sam :Canvas Mouse Events and Myself: PhysicsJS 
:)

**Comment by SAMdroid-apps** [comment]
Can you close the github issue? @walterbender?

**Comment by SAMdroid-apps** [comment]
This has been fixed, can somebody please CLOSE THE ISSUE!

**Comment by i5o** [comment]
Lets wait.

**Comment by i5o** [comment]
Thanks 🙏
