### ISSUE TITLE
loading images on a chromebook

### ISSUE THREAD

**Issue by walterbender** [walterbender/turtleblocksjs#153]
Images from the download folder on a chromebook do not load properly into image blocks or show properly with the show block. Images over the web work fine.

**Comment by ignaciouy** [comment]
https://github.com/walterbender/turtleblocksjs/pull/156

**Comment by ignaciouy** [comment]
works, again

Fixed in https://github.com/walterbender/turtleblocksjs/commit/96008713f07ddf4e8457a86ddbe7e5d1c97c2af3

there is a know bug.

**Comment by i5o** [comment]
@walterbender can we close this?
