### ISSUE TITLE
Tour messes things up on mobile

### ISSUE THREAD

**Issue by SAMdroid-apps** [walterbender/turtleblocksjs#160]
Joyride does not work on mobile... really.  Here are some pretty pictures:

![](https://i.imgur.com/0IaJHqn.png)

![](https://i.imgur.com/m5cQog8.png)

![](https://i.imgur.com/VdSV1cZ.png)

![](https://i.imgur.com/YSvOLad.png)

Full album:  https://imgur.com/a/Gl1E6

**Comment by walterbender** [comment]
Replaced with some native CreateJS code. Still a few alignment issues, but basically working now.
