### ISSUE TITLE
booleanOneArgBlock lost in transition to SVG

### ISSUE THREAD

**Issue by SAMdroid-apps** [walterbender/turtleblocksjs#193]
The transition to svg seems to have seen the `booleanOneArgBlock` get removed.  This is annoying, since I need it in TurtleStorm for my touch sensor block (bool out, text in).

@walterbender could you please re-add it?

**Comment by walterbender** [comment]
Done. https://github.com/walterbender/turtleblocksjs/commit/28b7b991ba0d375dc7b1fdd500278865674724e5
