### ISSUE TITLE
Plugin: Hide blocks from palettes

### ISSUE THREAD

**Issue by SAMdroid-apps** [walterbender/turtleblocksjs#197]
When I am developing a plugin, I might want to be able to hide blocks from the palette menu though keeping them in the code if used.  Use cases:

1.  Finding out whether a robot is an ev3 or NXT then hiding inappropriate blocks (eg. led only shows for NXT, gyro only for ev3)
2.  Removing blocks from the plugin without breaking existing programs

What do you think?

**Comment by walterbender** [comment]
There is a hidden flag you can use. (See for example, the unknown blocks in
basicblocks.js)
https://github.com/walterbender/turtleblocksjs/blob/master/js/basicblocks.js#L682

On Wed, Mar 11, 2015 at 2:41 AM, Sam <notifications@github.com> wrote:

> When I am developing a plugin, I might want to be able to hide blocks from
> the palette menu though keeping them in the code if used. Use cases:
>
>    1. Finding out whether a robot is an ev3 or NXT then hiding
>    inappropriate blocks (eg. led only shows for NXT, gyro only for ev3)
>    2. Removing blocks from the plugin without breaking existing programs
>
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/issues/197>.
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org
