### ISSUE TITLE
Sometimes long press puts menu in wrong place.

### ISSUE THREAD

**Issue by walterbender** [walterbender/turtleblocksjs#235]
It should always appear just above the current stack.

**Comment by sneh1234** [comment]
Long press on blocks ?

**Comment by walterbender** [comment]
Yes. That is the bug.

**Comment by sneh1234** [comment]
Sir, should it appear  above the current stack even after dragging that stack ?

**Comment by walterbender** [comment]
It should appear above the current stack position, whereever that may be,
but it will disappear as the stack is being dragged and only reappear after
another long press.

On Thu, Jan 14, 2016 at 4:54 AM, sneh1234 <notifications@github.com> wrote:

> Sir, should it appear above the current stack even after dragging that
> stack ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/turtleblocksjs/issues/235#issuecomment-171591240>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org
