### ISSUE TITLE
 Camera doesn't work on Android

### ISSUE THREAD

**Issue by walterbender** [walterbender/turtleblocksjs#236]
'nuf said

**Comment by tradzik** [comment]
It doesn't work on iOS 10 too (Safari).

**Comment by walterbender** [comment]
Chromium remains a problem as it is doing more rigorous checking:
getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
doUseCamera @ utils.js:571
Logo.runFromBlockNow @ logo.js:1047
(anonymous) @ logo.js:484
utils.js:577 DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

**Comment by tradzik** [comment]
You can try using `https` protocol @walterbender
