### ISSUE TITLE
Loudness block doesn't work on Windows 

### ISSUE THREAD

**Issue by walterbender** [walterbender/turtleblocksjs#238]
tested in Chrome

**Comment by i5o** [comment]
I think we should change p5, I will look on it

2015-10-14 10:48 GMT-03:00, Walter Bender <notifications@github.com>:
> tested in Chrome
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/walterbender/turtleblocksjs/issues/238


-- 
Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>

**Comment by tradzik** [comment]
it works on firefox, but I confirm this bug on chrome. I am on it.
