### ISSUE TITLE
Coordinates of turtle changes after resizing the window

### ISSUE THREAD

**Issue by sneh1234** [walterbender/turtleblocksjs#252]
Angle of turtle as well as its cartesian coordinate should not be changed  even after resizing the window. So labeling of bitmap should be changed to get correct coordinates.

**Comment by eohomegrownapps** [comment]
I'm participating in Google Code-In 2016. I have fixed bug #252 on Turtle Blocks - "Coordinates of turtle changes after resizing the window". The turtle will move to the correct position after resizing. Is it fine if the pen traces refresh when the window is resized? If so, how can I submit the bugfix?

**Comment by tradzik** [comment]
To be closed.
