### ISSUE TITLE
Pop up dialog box for Settings needs border

### ISSUE THREAD

**Issue by AbrahmAB** [walterbender/turtleblocksjs#256]
The settings pop up box which appears when clicked the settings icon on right panel.

![issue](https://cloud.githubusercontent.com/assets/16541261/13059247/d14f0d54-d44e-11e5-9919-059872b411bf.png)

**Comment by walterbender** [comment]
I don't understand what this issue is referring to, but please make sure you are running the current version of the code. This screenshot is not current.

**Comment by AbrahmAB** [comment]
The Popo-Up box was having the same background colour as the canvas. I found the issue solved in Branch url [http://rawgit.com/walterbender/turtleblocksjs/url/index.html](url) .
