### ISSUE TITLE
Transfer project to sugarlabs

### ISSUE THREAD

**Issue by davelab6** [walterbender/turtleblocksjs#274]
:)

**Comment by walterbender** [comment]
I need to figure out how to manage the gh_pages version of this repo after the transfer before I do the transfer as it is in active use.

**Comment by tradzik** [comment]
I think you can move project to SL namespace and start using SL project weburl, creating [a permanent redirect](https://help.github.com/articles/redirects-on-github-pages/) in your repo first (so all users accessing the old link will be redirected to the new one).

**Comment by walterbender** [comment]
I will make a Browse wrapper and include turtle as a submodule, which I then will transfer to sugarlabs. (Already did the same for Music Blocks: https://github.com/sugarlabs/music-blocks-embedded-activity)

**Comment by walterbender** [comment]
https://github.com/sugarlabs/turtle-blocks-embedded-activity
