### ISSUE TITLE
SVG output somewhat broken

### ISSUE THREAD

**Issue by walterbender** [walterbender/turtleblocksjs#276]
The included SVG is supposed to render as an R. Looks fine in TB, but not correct as SVG output.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" width="1055" height="868"><g transform="scale(1,1)"><rect x="0" y="0" height="868" width="1055" fill="rgb(146, 181, 200)"/><path d="M 544.86,549.7333333333333 624.9088888888889,549.7333333333333 728.1044444444444,819.7777777777778 896.8822222222223,819.7777777777778 778.2555555555556,527.5511111111111 C 845.7666666666667,499.58222222222224 896.8822222222223,439.7866666666667 896.8822222222223,318.26666666666665 896.8822222222223,298.97777777777776 C 896.8822222222223,99.33777777777777 758.0022222222223,67.5111111111111 635.5177777777778,67.5111111111111 388.62,67.5111111111111 388.62,819.7777777777778 544.86,819.7777777777778 544.86,549.7333333333333 " style="stroke-linecap:round;fill:none;stroke:rgba(255,0,104,1);stroke-width:4.822222222222222pt;" /><path d="M 544.86,414.7111111111111 544.86,202.53333333333333 642.2688888888889,202.53333333333333 C 684.7044444444444,202.53333333333333 738.7133333333334,218.92888888888888 738.7133333333334,303.8 738.7133333333334,313.44444444444446 C 738.7133333333334,398.31555555555553 684.7044444444444,414.7111111111111 642.2688888888889,414.7111111111111 544.86,414.7111111111111 " style="stroke-linecap:round;fill:none;stroke:rgba(255,0,104,1);stroke-width:4.822222222222222pt;" /></g></svg>
```

**Comment by walterbender** [comment]
`<svg` xmlns="http://www.w3.org/2000/svg" width="1055" height="868"><g transform="scale(1,1)"><rect x="0" y="0" height="868" width="1055" fill="rgb(146, 181, 200)"/><path d="M 544.86,549.7333333333333 624.9088888888889,549.7333333333333 728.1044444444444,819.7777777777778 896.8822222222223,819.7777777777778 778.2555555555556,527.5511111111111 C 845.7666666666667,499.58222222222224 896.8822222222223,439.7866666666667 896.8822222222223,318.26666666666665 896.8822222222223,298.97777777777776 C 896.8822222222223,99.33777777777777 758.0022222222223,67.5111111111111 635.5177777777778,67.5111111111111 388.62,67.5111111111111 388.62,819.7777777777778 544.86,819.7777777777778 544.86,549.7333333333333 " style="stroke-linecap:round;fill:none;stroke:rgba(255,0,104,1);stroke-width:4.822222222222222pt;" /><path d="M 544.86,414.7111111111111 544.86,202.53333333333333 642.2688888888889,202.53333333333333 C 684.7044444444444,202.53333333333333 738.7133333333334,218.92888888888888 738.7133333333334,303.8 738.7133333333334,313.44444444444446 C 738.7133333333334,398.31555555555553 684.7044444444444,414.7111111111111 642.2688888888889,414.7111111111111 544.86,414.7111111111111 " style="stroke-linecap:round;fill:none;stroke:rgba(255,0,104,1);stroke-width:4.822222222222222pt;" /></g></svg>`

**Comment by articuno12** [comment]
Can you please mention the affected file and also the expected output .

**Comment by walterbender** [comment]
https://walterbender.github.io/musicblocks/index.html?file=MusicBlocks_R.tb&run=True is the file that generated the error.

**Comment by walterbender** [comment]
FYI, I pushed this patch to the Music Blocks repo too. Thx.
