### ISSUE TITLE
Broken tool in media palette

### ISSUE THREAD

**Issue by EmilyOng** [walterbender/turtleblocksjs#292]
![buggy](https://cloud.githubusercontent.com/assets/21200681/21269268/0b991e80-c3ed-11e6-81e9-5612baa0a6a0.png)
![morebuggy](https://cloud.githubusercontent.com/assets/21200681/21269294/20f203c8-c3ed-11e6-8c6f-78afe7af9db0.png)

@walterbender

**Comment by walterbender** [comment]
oops. this is because of a macro expansion in palette.js that we don't want to use in Turtle. I will fix it.
