### ISSUE TITLE
The suggestion/error pop-up does not seem to disappear after the error has been corrected

### ISSUE THREAD

**Issue by Tabs16** [walterbender/turtleblocksjs#294]
In the attachment, when the action block has been removed or after the error is corrected,the pop-up doesn't disappear.
![t1](https://cloud.githubusercontent.com/assets/18511384/21307286/d4964894-c5fa-11e6-9c7a-f18a880f53a1.png)

**Comment by tradzik** [comment]
This error pop-up, as every error pop-up should disappear after you click it. Do you believe we should change that behaviour?

**Comment by Tabs16** [comment]
The problem arises that whenever we make and error and then correct it ,the pop-up doesnt disappear even if we continue to add other blocks,that is, it remains there.

**Comment by tradzik** [comment]
Partialy-implemented by making all error messages autodisappearing in 10 seconds (https://github.com/walterbender/turtleblocksjs/commit/b3f762d6700ae2e53514a2cc2a8e7c3db92e75a2). I don't really see any purpose of letting the code analyze whether the error persists automatically.
