### ISSUE TITLE
note to frequency block always returns NaN

### ISSUE THREAD

**Issue by tradzik** [walterbender/turtleblocksjs#308]
As in title, block (taken from media palette) seems to be always returning `NaN`. However, e.g. for A4 it should have been 440Hz (see picture below).

![Error block](http://i.imgur.com/NBjjCfK.png)

Browser: FF
Version of TBJS: `master` branch

**Comment by walterbender** [comment]
![screenshot from 2017-01-01 11-25-05](https://cloud.githubusercontent.com/assets/3996641/21581967/0d80780e-d015-11e6-9bca-f310a6568e9c.png)


Works for me. Hmm.

**Comment by tradzik** [comment]
@walterbender Could you try please any other note than a4?

**Comment by walterbender** [comment]
works fine for all the notes I tested.

**Comment by walterbender** [comment]
Oh. I just realized this is a Turtle bug, not  Music bug. I had been testing in Music Blocks.
