### ISSUE TITLE
p5.min.js not found

### ISSUE THREAD

**Issue by llaske** [walterbender/turtleblocksjs#331]
I've got a JavaScript error trying to read lib/p5.min.js.
This file is referenced on line 10 of index.html but don't exist in the repo.

<img width="1176" alt="image" src="https://cloud.githubusercontent.com/assets/981841/24323798/980c6508-117b-11e7-9586-d348cbeeac80.png">

**Comment by walterbender** [comment]
Hmm. It is there now.

https://github.com/walterbender/turtleblocksjs/blob/master/lib/p5.min.js

**Comment by walterbender** [comment]
Lionel: please reopen if this issue somehow persists.
