### ISSUE TITLE
About localization setup ? thanks

### ISSUE THREAD

**Issue by cryskytw** [walterbender/turtleblocksjs#335]
Hello all
I find this project has "localization.ini"
but I can't find any info about setup.
I find "translate.json" plugin. but can't work!!
thank all.

**Comment by walterbender** [comment]
Sorry to be so long in answering your question. Never got a notification from GH about this issue.
Translations are maintained in the po/ files. I run a script to update the localization.ini file from the po files whenever they are updated. (See https://github.com/walterbender/po-utils/blob/master/ConvertPOtoINI.py)

**Comment by walterbender** [comment]
The translation plugin is unrelated to localization. It is a set of blocks to access a translation service so you can use translation in a turtle project.

**Comment by walterbender** [comment]
Please reopen if you have more questions.
