### ISSUE TITLE
Loading plugins is broken in turtleblocksjs

### ISSUE THREAD

**Issue by garyservin** [walterbender/turtleblocksjs#339]
Starting from [this commit](https://github.com/walterbender/turtleblocksjs/commit/a33d835eb059354d7ba40ae3ac376211111247f2), where the way of loading plugins (dictionary instead of an array) changed, plugins can no longer be loaded in turtleblocks.

It seems there's a discrepancy between turtleblocks (which uses arrays) and musicblocks (which uses dictionaries).

What's weird is that the pluginify scripts has more functionalities on the turtleblocks side but still uses the array method for specifying the parts of the plugin. Which is the correct one?

**Comment by walterbender** [comment]
Hmm. I was able to load plugins (from the Music Blocks repo) into TurtleJS. Which suggests that the plugin files themselves are different. I will investigate further.

**Comment by walterbender** [comment]
I prefer the dictionary version over the list version. I will update pluginify.py in TurtleJS and update the JSON modes. (Note that the TurtleJS version supports a few more fields than the MB version -- onstart, onstop -- which I will add.

**Comment by garyservin** [comment]
Thanks @walterbender, I also prefer the dictionary version. Any reason why you've removed the onstart, onstop fields from here?

**Comment by walterbender** [comment]
> Any reason why you've removed the onstart, onstop fields from here?
Where is "here'?

**Comment by garyservin** [comment]
https://github.com/walterbender/turtleblocksjs/commit/cd1c70ca8bf7eee1364efde8f6e8da1756f8085c

**Comment by walterbender** [comment]
Oops. I missed that when I was migrating the MB version. Should be all set now.

**Comment by garyservin** [comment]
:+1:
