### ISSUE TITLE
Close icon is not  working.

### ISSUE THREAD

**Issue by satyamchaudharydev** [walterbender/turtleblocksjs#344]
![screen shot 2017-12-14 at 6 27 28 pm](https://user-images.githubusercontent.com/26341752/33993438-8e575ecc-e0fc-11e7-9b44-bd78ddb17ce1.png)
Close icon is not working.

**Comment by walterbender** [comment]
Can you tell me what version of Turtle you are running?

**Comment by satyamchaudharydev** [comment]
One on sugarizer. I am using Chrome 62 on Macbook Air.

**Comment by walterbender** [comment]
The one on Sugarizer is very old. Please test https://walterbender.github.io/turtleblocksjs

**Comment by satyamchaudharydev** [comment]
Sorry, didn't see that. I found bug in https://turtle.sugarlabs.org/

**Comment by walterbender** [comment]
I just updated turtle.sugarlabs.org... it was a bit stale. Thanks for pointing it out.

**Comment by walterbender** [comment]
I've got a bunch more updates to migrate over from Music Blocks, but I think this particular issue is resolved.
