### ISSUE TITLE
Making the utility buttons multicolumn 

### ISSUE THREAD

**Issue by jaskirat2000** [walterbender/turtleblocksjs#359]
images for this can be seen here :
(https://wiki.sugarlabs.org/images/3/3d/IMAGE.jpg )
( https://wiki.sugarlabs.org/images/f/f1/Image1.jpg )

It will help us to provide an appropriate space for making the preview window. So thumbnail window will be placed to the top and the utilities button will be placed under it in 3 rows and 3 columns.

**Comment by walterbender** [comment]
1x9 takes up the same amount of space as 3x3 and it is less intrusive. The preview window, if we add it, will be floating.

**Comment by jaskirat2000** [comment]
floating in what way ?

**Comment by walterbender** [comment]
https://www.w3schools.com/howto/howto_css_modals.asp

**Comment by jaskirat2000** [comment]
ok, thats work
