### ISSUE TITLE
Make the guide available from the help panel

### ISSUE THREAD

**Issue by jaskirat2000** [walterbender/turtleblocksjs#361]
images for this can be seen here :
(https://wiki.sugarlabs.org/images/3/3d/IMAGE.jpg )
( https://wiki.sugarlabs.org/images/f/f1/Image1.jpg

As in the program there exist a help button which only show the overview of the program ( like names of the buttons) but a user finds sometimes difficulty while programming so for this we will embed a program guide, stating all the commands, their functions, etc so that if a person finds hard to code and wants to know the next command then help can be taken through this guide.

**Comment by walterbender** [comment]
![screenshot from 2018-03-15 18-37-58](https://user-images.githubusercontent.com/3996641/37494609-0577e7d6-2880-11e8-80af-5dfee0c017e7.png)
