### ISSUE TITLE
Changes in the blocks

### ISSUE THREAD

**Issue by jaskirat2000** [walterbender/turtleblocksjs#363]
images for this can be seen here :
(https://wiki.sugarlabs.org/images/3/3d/IMAGE.jpg )
( https://wiki.sugarlabs.org/images/f/f1/Image1.jpg )

As the existing blocks a are large so reducing their size to upto so that it could have proper visibility of the texts written over them, by reducing the size we could have a appropriate workspace for doing programming.
Another change is making the blocks light in color, making the borders of the all blocks 80% black in color and making the text written over the blocks in bold.
![blocksui](https://user-images.githubusercontent.com/10228651/37407831-b378f4da-27c0-11e8-8c59-eb4c9f29a4ec.jpg)

**Comment by walterbender** [comment]
What is the rationale for these changes?
Note that there is already a mechanism for changing the block size.

**Comment by jaskirat2000** [comment]
The changes that have been made for the following
size reduced from the base code only to increase space.
colors have been made light so that text written on it can be read easily.
Text written on these blocks have been made bold and their size has been increased.
Borders have been made to black so as to enhance the particular block

**Comment by walterbender** [comment]
You've told me what you have proposed, but not why you have proposed it. And you did not address the question of what is inadequate about the current block scaling mechanism.

**Comment by jaskirat2000** [comment]
" size reduced from the base code only to increase space.
colors have been made light so that text written on it can be read easily.
Text written on these blocks have been made bold and their size has been increased to have better visibility and no mixing of colors.
Borders have been made to black so as to enhance the particular block."
These are the only changes with reason that have been implemented here.

**Comment by walterbender** [comment]
The literature suggests that there is little impact in increasing value contrast for legibility after about 2-3 Munsell value steps. We have more than that amount of contrast already.

Bold fonts don't increase legibility, especially when size is taken into consideration.

How do black borders enhance?

In any case, I am in favor of allowing the user to select colors for blocks and other aspects of the interface. Should be part of https://github.com/walterbender/musicblocks/issues/714
