### ISSUE TITLE
Making a side column slider for showing other buttons when cursor is placed on it

### ISSUE THREAD

**Issue by jaskirat2000** [walterbender/turtleblocksjs#364]
images for this can be seen here :
(https://wiki.sugarlabs.org/images/3/3d/IMAGE.jpg )
( https://wiki.sugarlabs.org/images/f/f1/Image1.jpg )

As proposed in above design, Making side column which include thumbnail window and other utility buttons . so for increasing the more space for programming we will add a small arrow like this to the right top so that when a user moves its cursor on it . the right hand side column get automatically open, showing the Preview window and other utility buttons and when a user remove cursor from it, it gets automatically close.

This is the image when it is opened.
![im1](https://user-images.githubusercontent.com/10228651/37407993-2d3c3a20-27c1-11e8-835a-8565ef1cee0e.jpg)

This is the image when it is closed and there is space for programming. When the cursor moves on this yellow part it gets automatically open and then a user can choose anything.
![im2](https://user-images.githubusercontent.com/10228651/37408026-4243598a-27c1-11e8-8fd6-d10bd40a10fe.jpg)

**Comment by walterbender** [comment]
How is this an improvement over the existing menu collapse button?

![screenshot from 2018-03-15 18-34-59](https://user-images.githubusercontent.com/3996641/37494532-9c784028-287f-11e8-808c-d90b8f00938a.png)
![screenshot from 2018-03-15 18-34-39](https://user-images.githubusercontent.com/3996641/37494533-9c862ca6-287f-11e8-80f4-be48296ec224.png)

**Comment by jaskirat2000** [comment]
that feature of adding the slide is added because of the thumbnail window. So that it also get proper space

**Comment by walterbender** [comment]
You did not answer my question. We already have a mechanism for hiding the toolbar. Why is the proposed method preferred?

**Comment by jaskirat2000** [comment]
just to enhance the look within the program as i think i have designed it for more enhanced things ...,1 but it can be fine. but i think instead of scrolling towards left will look better than towards upside. thats optional if the Thumbnail window is added.
