### ISSUE TITLE
turtle can be draged and moved from centre position

### ISSUE THREAD

**Issue by vaibhavdaren** [walterbender/turtleblocksjs#366]
The turtle can be dragged to any location.
I was planning on creating interactive exercises for turtleblockjs while experimenting I noticed that the turtle can be dragged with the mouse to any location. This defeats the purpose of pen up and pen down.
![screenshot 12](https://user-images.githubusercontent.com/17678138/37869541-134b060c-2fdf-11e8-9cd0-3e3077547da5.png)

**Comment by walterbender** [comment]
How does being able to reposition the turtle "defeat the purpose of pen up and pen down"?

**Comment by vaibhavdaren** [comment]
I was planning to design interactive exercises for  teaching turtle. 
In the module where we introduce pen up and down. 
to reach the starting point we needed  to use pen up and down
![chiaok](https://user-images.githubusercontent.com/17678138/37869674-f0dff23c-2fe1-11e8-9884-b85d2f1972e5.png)
but if we can just drag the turtle it defeats the purpose.

**Comment by walterbender** [comment]
I don't exactly understand what the task is, but if you want the user to not drag the turtle, then say, "don't drag the turtle/" If you don't trust the user, then reposition the turtle if they drag it.

**Comment by vaibhavdaren** [comment]
understood :+1:
