### ISSUE TITLE
setting variable values

### ISSUE THREAD

**Issue by alexKleider** [walterbender/turtleblocksjs#45]
When picking a block such as 'forward' it comes with a default argument.  Modifying such a default seems very erratic.  It appears that one has to detach the value box from the parent block, change the value and then reattach it.  Moving the block often results in the whole screen scrolling downwards.  Entering a new value makes all other values return to their defaults but only as shown on the screen.  The actual values are preserved.
Currently I've got myself into a state where the value entry box seems to jump out of the container and I seem unable to get the value back where it belongs.

**Comment by walterbender** [comment]
I think this issue has been resolved. Please reopen if it is still an issue.
